name: ocr_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7
  google_ml_kit: ^0.13.0
  vector_math: ^2.1.2
  cupertino_icons: ^1.0.6
  file_picker: ^5.0.1
  pdf_render: ^1.4.12
  flutter_pdfview: ^1.0.0
  pdf_image_renderer: ^0.7.0
  pdf: ^3.6.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  http: ^1.2.2
  image: ^4.3.0
  image_cropper: ^1.0.0
  fluttertoast: ^8.0.9
  crop_your_image:
    git:
      url: https://github.com/harshitkar/crop_your_image.git
      ref: main
  uuid: ^3.0.5
  intl: ^0.18.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
